version: 2.1

parameters:
  build-ui:
    type: boolean
    default: false
  build-api:
    type: boolean
    default: false

jobs:
  always-run-job:
    docker:
      - image: cimg/base:2022.11
    steps:
      - run: echo I will always run!

  build-ui-job:
    docker:
      - image: cimg/base:2022.11
    steps:
      - run:
          name: Something has changed in UI
          command: echo Something in UI has changed

  build-api-job:
    docker:
      - image: cimg/base:2022.11
    steps:
      - run:
          name: Something has changed in API
          command: echo Somethin in API has changed

workflows:
  always-run:
    jobs:
      - always-run-job

  build-ui:
    when: << pipeline.parameters.build-ui >>
    jobs:
      - build-ui-job

  build-api:
    when: << pipeline.parameters.build-api >>
    jobs:
      - build-api-job
